// Auto-generated by ChatGPT: merged FULL router + Apple-like UI + collapsible Activity
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using System.Windows.Forms;
using System.Drawing;
using System.Drawing.Drawing2D;

namespace DesklyPC;

public partial class Form1 : Form
{
    private readonly TcpJsonServer _server = new();
    private readonly PairingManager _pairing = new();
    private readonly SleepTimerService _sleepTimer = new();

    // ✅ UDP discovery
    private UdpDiscoveryServer? _discovery;
    private const int UDP_DISCOVERY_PORT = 5051;
    private string _serverId = "";

    private readonly System.Windows.Forms.Timer _uiTimer = new();
    private readonly System.Windows.Forms.Timer _sleepUiTimer = new();

    private string? _lastGeneratedPin;

    // ✅ track running state (aby sme neštartovali 2x)
    private bool _isRunning = false;

    // Night
    private int _lastNightNonZeroIntensity = 35;

    // Quiet (UI-side cache – aby toggle fungoval aj keď QuietModeService.GetState() niekedy vracia starú hodnotu)
    private bool _quietUiEnabled = false;

    // Smooth transitions (external brightness + night intensity)
    private readonly BrightnessSmoother _brightnessSmoother;
    private readonly NightSmoother _nightSmoother;

    // =========================
    // LOG SETTINGS
    // =========================
    private const bool DEBUG_LOG = false;     // keď chceš detail, daj true
    private const bool ADVANCED_UI = false;   // Start/Stop/Port sú advanced (default skryté)

    private enum LogLevel { Info, Ok, Warn, Error }

    // last states to avoid spam
    private (bool running, int remainingSeconds, string action) _lastTimerStatus = (false, -1, "");
    private DateTime _lastThrottledLogAt = DateTime.MinValue;
    private string _lastThrottledLogKey = "";
    private bool? _lastAuthOk = null;

    // Unknown type throttling
    private DateTime _lastUnknownLogAt = DateTime.MinValue;
    private string _lastUnknownType = "";

    // Activity (collapsible)
    private bool _activityExpanded = true;
    private int _activityExpandedHeight = 0;
    private int _activityCollapsedHeight = 0;

    public Form1()
    {
        InitializeComponent();

        // --- Apple-like status dot (circle) ---
        try
        {
            if (lblStatusChip != null)
            {
                using var gp = new GraphicsPath();
                gp.AddEllipse(0, 0, lblStatusChip.Width, lblStatusChip.Height);
                lblStatusChip.Region = new Region(gp);
                lblStatusChip.Text = "";
            }
        }
        catch { /* ignore */ }

        // Title text runtime-safe
        TrySetText("lblTitle", "desklyPC™");
        TrySetText("lblAppName", "desklyPC™");
        TrySetText("lblHeaderTitle", "desklyPC™");

        Text = "DesklyPC™";
        MinimizeBox = true;
        ShowInTaskbar = true;

        // Minimize-to-tray (keeps server running)
        Resize += (_, __) =>
        {
            if (WindowState == FormWindowState.Minimized)
            {
                Hide();
                ShowInTaskbar = false;
            }
        };

        // ✅ stable server id + discovery init
        _serverId = LoadOrCreateServerId();
        var pcName = Environment.MachineName;
        _discovery = new UdpDiscoveryServer(_serverId, pcName);
        _discovery.Log += AppendLog;

        // Night/Quiet services
        NightModeService.Init(this);
        QuietModeService.Init(this);

        // Smoothers (inject logger so failures are visible)
        _brightnessSmoother = new BrightnessSmoother((lvl, msg) => WriteLog(lvl, msg));
        _nightSmoother = new NightSmoother();

        _brightnessSmoother.Start();
        _nightSmoother.Start();

        // Sync UI cache with service at startup
        _quietUiEnabled = QuietModeService.GetState();

        numPort.Minimum = 1024;
        numPort.Maximum = 65535;
        numPort.Value = 5050;

        _server.Log += AppendLog;
        _server.HandleRequest += HandleIncomingRequest;

        lblIpValue.Text = GetLocalIpv4() ?? "unknown";
        SetRunningUi(false);

        // Activity collapsible
        InitActivityCollapsible();

        // ✅ AUTO START servera po spustení appky
        Shown += (_, __) => StartServerAndDiscovery();

        // PIN countdown (1s)
        _uiTimer.Interval = 1000;
        _uiTimer.Tick += (_, _) =>
        {
            if (_pairing.HasValidPin)
            {
                var sec = _pairing.PinSecondsRemaining();
                if (sec > 0)
                {
                    lblPinValue.Text = string.IsNullOrWhiteSpace(_lastGeneratedPin)
                        ? $"{sec}s"
                        : $"{_lastGeneratedPin} · {sec}s";
                }
                else
                {
                    lblPinValue.Text = "------";
                }
            }
        };
        _uiTimer.Start();

        // ✅ Timer UI log: len zmeny + posledných 10s
        _sleepUiTimer.Interval = 1000;
        _sleepUiTimer.Tick += (_, _) =>
        {
            var st = _sleepTimer.GetStatus();
            var action = st.action ?? "";

            if (st.running != _lastTimerStatus.running || action != _lastTimerStatus.action)
            {
                if (st.running)
                    LogInfo($"Timer spustený: {HumanTimerAction(action)} (zostáva {FormatSeconds(st.remainingSeconds)})");
                else
                    LogInfo("Timer zastavený");
            }

            if (st.running && st.remainingSeconds <= 10 && st.remainingSeconds != _lastTimerStatus.remainingSeconds)
            {
                LogWarn($"Timer: {HumanTimerAction(action)} za {st.remainingSeconds}s");
            }

            _lastTimerStatus = (st.running, st.remainingSeconds, action);
        };
        _sleepUiTimer.Start();

        // načítaj night state
        var (_, inten) = NightModeService.GetState();
        if (inten > 0) _lastNightNonZeroIntensity = inten;

        FormClosing += (_, e) =>
        {
            // ✅ Klik na X = iba schovať do tray
            if (!Program.IsRealExit && e.CloseReason == CloseReason.UserClosing)
            {
                e.Cancel = true;
                Hide();
                ShowInTaskbar = false;
                return;
            }

            _uiTimer.Stop();
            _sleepUiTimer.Stop();
            _sleepTimer.Cancel();

            _discovery?.Stop();
            _server.Stop();

            if (e.CloseReason == CloseReason.WindowsShutDown)
                return;

            NightModeService.Shutdown();
            _brightnessSmoother.Stop();
            _nightSmoother.Stop();

            QuietModeService.Shutdown();
        };
    }

    // =========================
    // UI helper
    // =========================
    private void TrySetText(string controlName, string text)
    {
        try
        {
            var c = Controls.Find(controlName, true).FirstOrDefault();
            if (c is Label lbl) lbl.Text = text;
            else if (c is Button btn) btn.Text = text;
            else if (c is TextBox tb) tb.Text = text;
        }
        catch { /* ignore */ }
    }

    // =========================
    // START/STOP
    // =========================
    private void StartServerAndDiscovery()
    {
        if (_isRunning) return;

        var port = (int)numPort.Value;

        _server.Start(port);
        LogOk("Pripravené na ovládanie");

        _discovery?.Start(UDP_DISCOVERY_PORT, port);
        LogInfo("Vyhľadávanie zariadení zapnuté");

        lblIpValue.Text = GetLocalIpv4() ?? "unknown";
        SetRunningUi(true);
    }

    private void btnStart_Click(object sender, EventArgs e) => StartServerAndDiscovery();

    private void btnStop_Click(object sender, EventArgs e)
    {
        _server.Stop();
        _sleepTimer.Cancel();
        _discovery?.Stop();

        LogWarn("Server zastavený");
        SetRunningUi(false);

        lblPinValue.Text = "------";
        _lastGeneratedPin = null;
    }

    private void btnPair_Click(object sender, EventArgs e)
    {
        var pin = _pairing.GeneratePin(TimeSpan.FromSeconds(120));
        _lastGeneratedPin = pin;

        lblPinValue.Text = pin;
        LogInfo($"Kód: {pin} (platí 120s)");
    }

    // =========================
    // ACTIVITY (collapsible)
    // =========================
    private void InitActivityCollapsible()
    {
        try
        {
            Shown += (_, __) =>
            {
                _activityExpandedHeight = cardLog?.Height ?? 0;

                if (cardLog != null && lblLogTitle != null)
                {
                    _activityCollapsedHeight = Math.Max(56, lblLogTitle.Bottom + 18);
                    SetActivityExpanded(true, log: false);
                }
            };

            if (lblLogTitle != null)
            {
                lblLogTitle.Cursor = Cursors.Hand;
                lblLogTitle.Text = "Aktivita ▾";
                lblLogTitle.Click += (_, __) => ToggleActivity();
            }
        }
        catch { /* ignore */ }
    }

    private void ToggleActivity() => SetActivityExpanded(!_activityExpanded, log: false);

    private void SetActivityExpanded(bool expanded, bool log)
    {
        _activityExpanded = expanded;

        try
        {
            if (lblLogTitle != null)
                lblLogTitle.Text = expanded ? "Aktivita ▾" : "Aktivita ▸";

            if (txtLog != null)
                txtLog.Visible = expanded;

            if (cardLog != null)
            {
                if (_activityExpandedHeight <= 0) _activityExpandedHeight = cardLog.Height;
                if (_activityCollapsedHeight <= 0 && lblLogTitle != null)
                    _activityCollapsedHeight = Math.Max(56, lblLogTitle.Bottom + 18);

                cardLog.Height = expanded ? _activityExpandedHeight : _activityCollapsedHeight;
            }

            if (log) LogInfo(expanded ? "Aktivita rozbalená" : "Aktivita zbalená");
        }
        catch { /* ignore */ }
    }

    // =========================
    // External brightness capability test (simple)
    // =========================
    private void btnTestExternalBrightness_Click(object sender, EventArgs e)
    {
        RunExternalBrightnessCapabilityTest(logToUi: true);
    }

    private ExternalBrightnessCapability.CapabilityResult RunExternalBrightnessCapabilityTest(bool logToUi)
    {
        if (logToUi) LogInfo("Overujem podporu ovládania jasu externého monitora...");

        var res = ExternalBrightnessCapability.Test();

        if (logToUi)
        {
            if (res.Supported) LogOk("Externý monitor podporuje ovládanie jasu cez aplikáciu ✓");
            else LogWarn("Externý monitor nepodporuje ovládanie jasu cez aplikáciu");

            try
            {
                if (lblExternalBrightnessStatus != null)
                {
                    lblExternalBrightnessStatus.Text = res.Supported
                        ? "Externý monitor podporuje ovládanie jasu"
                        : "Externý monitor nepodporuje ovládanie jasu";
                }
            }
            catch { /* ignore */ }
        }

        return res;
    }

    // =========================
    // Quiet button (PC-side)
    // =========================
    private void btnQuiet_Click(object sender, EventArgs e)
    {
        var requested = !_quietUiEnabled;

        var ok = QuietModeService.TrySet(requested, out var msg);

        if (ok)
        {
            _quietUiEnabled = requested;
            LogOk($"Tichý režim: {(requested ? "ZAP" : "VYP")}");
            return;
        }

        LogErr($"Tichý režim zlyhal: {msg}");

        if (requested &&
            (msg.Contains("správca", StringComparison.OrdinalIgnoreCase) ||
             msg.Contains("Administrator", StringComparison.OrdinalIgnoreCase)))
        {
            var res = MessageBox.Show(
                "Tichý režim vyžaduje spustenie ako správca.\nChceš reštartnúť DesklyPC ako Administrator?",
                "DesklyPC",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning
            );

            if (res == DialogResult.Yes)
                Program.RestartAsAdmin();
        }
    }

    private void SetRunningUi(bool running)
    {
        _isRunning = running;

        btnStart.Enabled = !running;
        btnStop.Enabled = running;
        btnPair.Enabled = running;
        numPort.Enabled = !running;

        btnStart.Visible = ADVANCED_UI;
        btnStop.Visible = ADVANCED_UI;
        numPort.Visible = ADVANCED_UI;

        if (running)
        {
            lblStatusChip.Text = "";
            lblStatusChip.BackColor = Color.FromArgb(76, 217, 100); // green
            if (lblStatusText != null) lblStatusText.Text = "Pripravené";
            if (lblStatusText != null) lblStatusText.ForeColor = Color.FromArgb(200, 255, 255, 255);
        }
        else
        {
            lblStatusChip.Text = "";
            lblStatusChip.BackColor = Color.FromArgb(123, 127, 134); // gray
            if (lblStatusText != null) lblStatusText.Text = "Vypnuté";
            if (lblStatusText != null) lblStatusText.ForeColor = Color.FromArgb(160, 163, 170);
        }
    }

    // =========================
    // LOG (raw -> human)
    // =========================
    private void AppendLog(string rawLine)
    {
        var (lvl, msg, shouldLog) = NormalizeLog(rawLine);
        if (!shouldLog) return;

        WriteLog(lvl, msg);
    }

    private void LogInfo(string msg) => WriteLog(LogLevel.Info, msg);
    private void LogOk(string msg) => WriteLog(LogLevel.Ok, msg);
    private void LogWarn(string msg) => WriteLog(LogLevel.Warn, msg);
    private void LogErr(string msg) => WriteLog(LogLevel.Error, msg);

    private void WriteLog(LogLevel lvl, string msg)
    {
        if (InvokeRequired)
        {
            BeginInvoke(new Action(() => WriteLog(lvl, msg)));
            return;
        }

        var color = lvl switch
        {
            LogLevel.Ok => Color.FromArgb(180, 255, 200),
            LogLevel.Warn => Color.FromArgb(255, 210, 160),
            LogLevel.Error => Color.FromArgb(255, 140, 140),
            _ => Color.FromArgb(220, 220, 230),
        };

        txtLog.SelectionStart = txtLog.TextLength;
        txtLog.SelectionLength = 0;
        txtLog.SelectionColor = color;
        txtLog.AppendText($"{DateTime.Now:HH:mm:ss} {msg}{Environment.NewLine}");
        txtLog.SelectionColor = txtLog.ForeColor;
        txtLog.ScrollToCaret();
    }

    private static (LogLevel lvl, string msg, bool shouldLog) NormalizeLog(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return (LogLevel.Info, "", false);

        var line = raw.Trim();

        // wire spam
        if (line.StartsWith("[IN ") || line.StartsWith("[OUT]") || line.StartsWith("[IN]"))
            return (LogLevel.Info, "", DEBUG_LOG);

        if (line.Contains("[CONN] Connected", StringComparison.OrdinalIgnoreCase))
            return (LogLevel.Ok, "Zariadenie pripojené", true);

        if (line.Contains("[CONN] Disconnected", StringComparison.OrdinalIgnoreCase))
            return (LogLevel.Warn, "Zariadenie odpojené", true);

        if (line.Contains("Unauthorized", StringComparison.OrdinalIgnoreCase))
            return (LogLevel.Warn, "Zariadenie nie je spárované", true);

        if (line.Contains("Bad JSON", StringComparison.OrdinalIgnoreCase))
            return (LogLevel.Error, "Chyba komunikácie (neplatné dáta)", true);

        if (line.Contains("[ERROR]", StringComparison.OrdinalIgnoreCase))
            return (LogLevel.Error, line.Replace("[ERROR]", "Chyba:", StringComparison.OrdinalIgnoreCase).Trim(), true);

        return (LogLevel.Info, line, DEBUG_LOG);
    }

    private static string? GetLocalIpv4()
    {
        try
        {
            var host = Dns.GetHostEntry(Dns.GetHostName());
            var addr = host.AddressList.FirstOrDefault(a => a.AddressFamily == AddressFamily.InterNetwork);
            return addr?.ToString();
        }
        catch { return null; }
    }

    // =========================
    // RID helpers
    // =========================
    private static string? GetRid(JsonElement root)
    {
        if (root.TryGetProperty("rid", out var ridEl) && ridEl.ValueKind == JsonValueKind.String)
            return ridEl.GetString();
        return null;
    }

    private static string WithRid(string requestJson, object responseObj)
    {
        using var doc = JsonDocument.Parse(requestJson);
        var rid = GetRid(doc.RootElement);

        if (string.IsNullOrEmpty(rid))
            return JsonSerializer.Serialize(responseObj);

        var json = JsonSerializer.SerializeToElement(responseObj);

        using var ms = new MemoryStream();
        using var writer = new Utf8JsonWriter(ms);

        writer.WriteStartObject();
        writer.WriteString("rid", rid);

        foreach (var prop in json.EnumerateObject())
            prop.WriteTo(writer);

        writer.WriteEndObject();
        writer.Flush();

        return Encoding.UTF8.GetString(ms.ToArray());
    }

    // =========================
    // Payload helpers
    // =========================
    private static string? GetTokenFromPayload(JsonElement payload)
    {
        if (payload.ValueKind != JsonValueKind.Object) return null;
        if (payload.TryGetProperty("token", out var tokenEl))
            return tokenEl.GetString();
        return null;
    }

    private static string GetDisplayIdFromPayload(JsonElement payload)
    {
        if (payload.ValueKind != JsonValueKind.Object) return "all";

        if (payload.TryGetProperty("displayId", out var idEl) && idEl.ValueKind == JsonValueKind.String)
        {
            var s = (idEl.GetString() ?? "").Trim();
            if (!string.IsNullOrEmpty(s)) return s;
        }

        if (!payload.TryGetProperty("target", out var tEl) || tEl.ValueKind != JsonValueKind.String)
            return "all";

        var t = (tEl.GetString() ?? "all").Trim().ToLowerInvariant();
        return t switch
        {
            "internal" or "laptop" => "internal",
            "2" or "display2" or "d2" => "ddc_2",
            "1" or "display1" or "d1" => "ddc_1",
            "all" or "both" or "1+2" or "12" => "all",
            _ => "all",
        };
    }

    private static bool TryGetBool(JsonElement payload, string prop, bool fallback)
    {
        if (payload.ValueKind != JsonValueKind.Object) return fallback;
        if (!payload.TryGetProperty(prop, out var el)) return fallback;

        return el.ValueKind switch
        {
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.String => bool.TryParse(el.GetString(), out var b) ? b : fallback,
            JsonValueKind.Number => el.TryGetInt32(out var n) ? (n != 0) : fallback,
            _ => fallback
        };
    }

    private static bool TryGetBoolNullable(JsonElement payload, string prop, out bool value)
    {
        value = false;
        if (payload.ValueKind != JsonValueKind.Object) return false;
        if (!payload.TryGetProperty(prop, out var el)) return false;

        switch (el.ValueKind)
        {
            case JsonValueKind.True: value = true; return true;
            case JsonValueKind.False: value = false; return true;
            case JsonValueKind.String: return bool.TryParse(el.GetString(), out value);
            case JsonValueKind.Number:
                if (el.TryGetInt32(out var n)) { value = n != 0; return true; }
                return false;
            default:
                return false;
        }
    }

    private static int TryGetInt(JsonElement payload, string prop, int fallback)
    {
        if (payload.ValueKind != JsonValueKind.Object) return fallback;
        if (!payload.TryGetProperty(prop, out var el)) return fallback;

        if (el.ValueKind == JsonValueKind.Number && el.TryGetInt32(out var v)) return v;
        if (el.ValueKind == JsonValueKind.String && int.TryParse(el.GetString(), out var vs)) return vs;
        return fallback;
    }

    // =========================
    // Brightness routing
    // =========================
    private static bool TryGetBrightnessByDisplayId(string displayId, out int value0to100, out string mechanism, out string message)
    {
        value0to100 = -1;
        mechanism = "UNKNOWN";
        message = "";

        if (string.Equals(displayId, "internal", StringComparison.OrdinalIgnoreCase))
        {
            mechanism = "WMI";
            return DisplayService.TryGetInternalBrightness(out value0to100, out message);
        }

        if (DisplayService.TryResolveDdcIndex(displayId, out var idx1))
        {
            mechanism = "DDC/CI";
            return MonitorBrightness.TryGet(idx1, out value0to100, out message);
        }

        if (displayId.StartsWith("ddc_", StringComparison.OrdinalIgnoreCase)
            && int.TryParse(displayId.Substring(4), out var idxFallback))
        {
            mechanism = "DDC/CI";
            return MonitorBrightness.TryGet(idxFallback, out value0to100, out message);
        }

        message = "Unknown display";
        return false;
    }

    private static bool TrySetBrightnessByDisplayId(string displayId, int value0to100, out string mechanism, out string message)
    {
        mechanism = "UNKNOWN";
        message = "";
        value0to100 = Math.Clamp(value0to100, 0, 100);

        if (string.Equals(displayId, "internal", StringComparison.OrdinalIgnoreCase))
        {
            mechanism = "WMI";
            return DisplayService.TrySetInternalBrightness(value0to100, out message);
        }

        if (DisplayService.TryResolveDdcIndex(displayId, out var idx1))
        {
            mechanism = "DDC/CI";
            return MonitorBrightness.TrySet(idx1, value0to100, out message);
        }

        if (displayId.StartsWith("ddc_", StringComparison.OrdinalIgnoreCase)
            && int.TryParse(displayId.Substring(4), out var idxFallback))
        {
            mechanism = "DDC/CI";
            return MonitorBrightness.TrySet(idxFallback, value0to100, out message);
        }

        message = "Unknown display";
        return false;
    }

    private static string HumanDisplay(string displayId)
    {
        if (string.Equals(displayId, "internal", StringComparison.OrdinalIgnoreCase))
            return "Interný displej";
        if (string.Equals(displayId, "all", StringComparison.OrdinalIgnoreCase))
            return "Všetky displeje";
        return "Externý monitor";
    }

    // =========================
    // JSON ROUTER (FULL)
    // =========================
    private string HandleIncomingRequest(string jsonLine)
    {
        try
        {
            using var doc = JsonDocument.Parse(jsonLine);
            var root = doc.RootElement;

            if (!root.TryGetProperty("type", out var typeEl))
                return WithRid(jsonLine, new { type = "response", ok = false, message = "Missing type" });

            var type = typeEl.GetString() ?? "";

            if (type == "pair_status")
            {
                return WithRid(jsonLine, new
                {
                    type = "pair_status_response",
                    ok = true,
                    data = new
                    {
                        hasValidPin = _pairing.HasValidPin,
                        pinSecondsRemaining = _pairing.PinSecondsRemaining(),
                        validTokensCount = _pairing.ValidTokensCount
                    }
                });
            }

            if (type == "pair_request")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "pair_response", ok = false, message = "Missing payload" });

                var pin = payload.TryGetProperty("pin", out var pinEl) ? (pinEl.GetString() ?? "") : "";
                var (ok, token, message) = _pairing.TryPair(pin);

                if (ok)
                {
                    LogOk("Spárovanie úspešné");
                    return WithRid(jsonLine, new { type = "pair_response", ok = true, message, data = new { token } });
                }

                LogWarn("Spárovanie zlyhalo");
                return WithRid(jsonLine, new { type = "pair_response", ok = false, message });
            }

            if (type == "auth_request")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "auth_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                var ok = _pairing.IsTokenValid(token);

                if (_lastAuthOk != ok)
                {
                    _lastAuthOk = ok;
                    if (ok) LogOk("Autorizácia OK");
                    else LogWarn("Autorizácia zlyhala");
                }

                return WithRid(jsonLine, new { type = "auth_response", ok, message = ok ? "Authorized" : "Unauthorized" });
            }

            if (type == "display_list")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "display_list_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "display_list_response", ok = false, message = "Unauthorized" });

                var displays = DisplayService.GetDisplays();
                return WithRid(jsonLine, new { type = "display_list_response", ok = true, message = "OK", data = new { displays } });
            }

            if (type == "capabilities_external_brightness")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "capabilities_external_brightness_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "capabilities_external_brightness_response", ok = false, message = "Unauthorized" });

                var res = RunExternalBrightnessCapabilityTest(logToUi: false);

                var monitors = res.Monitors.Select(m => new
                {
                    ddcIndex = m.DdcIndex,
                    name = string.IsNullOrWhiteSpace(m.Name) ? "Unknown monitor" : m.Name,
                    ddcci = m.DdcciAvailable,
                    canGet = m.CanGet,
                    canSet = m.CanSet,
                    note = m.Note ?? ""
                }).ToArray();

                return WithRid(jsonLine, new
                {
                    type = "capabilities_external_brightness_response",
                    ok = true,
                    message = "OK",
                    data = new { supported = res.Supported, monitors }
                });
            }

            if (type == "ping_secure")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "response", ok = false, message = "Unauthorized" });

                return WithRid(jsonLine, new { type = "response", ok = true, message = "pong" });
            }

            if (type is "power_lock" or "power_sleep" or "power_shutdown" or "power_restart")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "power_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "power_response", ok = false, message = "Unauthorized" });

                bool ok;
                string msg;
                string human;

                switch (type)
                {
                    case "power_lock":
                        ok = SystemActions.LockPc();
                        msg = ok ? "Locked" : "Lock failed";
                        human = ok ? "PC uzamknuté" : "Nepodarilo sa uzamknúť PC";
                        break;
                    case "power_sleep":
                        ok = SystemActions.SleepPc();
                        msg = ok ? "Sleeping" : "Sleep failed";
                        human = ok ? "PC uspávané" : "Nepodarilo sa uspať PC";
                        break;
                    case "power_shutdown":
                        ok = SystemActions.ShutdownPc();
                        msg = ok ? "Shutting down" : "Shutdown failed";
                        human = ok ? "PC sa vypína" : "Nepodarilo sa vypnúť PC";
                        break;
                    case "power_restart":
                        ok = SystemActions.RestartPc();
                        msg = ok ? "Restarting" : "Restart failed";
                        human = ok ? "PC sa reštartuje" : "Nepodarilo sa reštartovať PC";
                        break;
                    default:
                        ok = false; msg = "Unknown power"; human = "Neznáma akcia";
                        break;
                }

                if (ok) LogInfo(human);
                else LogErr(human);

                return WithRid(jsonLine, new { type = "power_response", ok, message = msg });
            }

            if (type == "sleep_timer_set")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "sleep_timer_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "sleep_timer_response", ok = false, message = "Unauthorized" });

                if (!payload.TryGetProperty("seconds", out var secEl) || secEl.ValueKind != JsonValueKind.Number)
                    return WithRid(jsonLine, new { type = "sleep_timer_response", ok = false, message = "Missing seconds" });

                var seconds = secEl.GetInt32();
                var action = payload.TryGetProperty("action", out var actEl) ? (actEl.GetString() ?? "sleep") : "sleep";
                action = action == "shutdown" ? "shutdown" : "sleep";

                _sleepTimer.Set(seconds, action);
                LogOk($"Timer nastavený: {FormatSeconds(seconds)} ({HumanTimerAction(action)})");

                var st = _sleepTimer.GetStatus();
                return WithRid(jsonLine, new
                {
                    type = "sleep_timer_response",
                    ok = true,
                    message = "Timer set",
                    data = new { running = st.running, remainingSeconds = st.remainingSeconds, action = st.action }
                });
            }

            if (type == "sleep_timer_cancel")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "sleep_timer_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "sleep_timer_response", ok = false, message = "Unauthorized" });

                _sleepTimer.Cancel();
                LogInfo("Timer zrušený");

                return WithRid(jsonLine, new { type = "sleep_timer_response", ok = true, message = "Timer cancelled" });
            }

            if (type == "sleep_timer_status")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "sleep_timer_status_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "sleep_timer_status_response", ok = false, message = "Unauthorized" });

                var st = _sleepTimer.GetStatus();
                return WithRid(jsonLine, new { type = "sleep_timer_status_response", ok = true, data = new { running = st.running, remainingSeconds = st.remainingSeconds, action = st.action } });
            }

            if (type == "volume_get" || type == "volume_set" || type == "mute_toggle")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "audio_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "audio_response", ok = false, message = "Unauthorized" });

                if (type == "volume_get")
                {
                    var vol = SystemActions.GetVolume();
                    var muted = SystemActions.GetMute();
                    return WithRid(jsonLine, new { type = "audio_response", ok = true, message = "OK", data = new { volume = vol, muted } });
                }

                if (type == "volume_set")
                {
                    if (!payload.TryGetProperty("volume", out var volEl) || volEl.ValueKind != JsonValueKind.Number)
                        return WithRid(jsonLine, new { type = "audio_response", ok = false, message = "Missing volume" });

                    var volume = volEl.GetInt32();
                    SystemActions.SetVolume(volume);

                    var now = DateTime.UtcNow;
                    var key = $"vol:{Math.Clamp(volume, 0, 100)}";
                    if (now - _lastThrottledLogAt > TimeSpan.FromMilliseconds(700) || _lastThrottledLogKey != key)
                    {
                        _lastThrottledLogAt = now;
                        _lastThrottledLogKey = key;
                        LogInfo($"Hlasitosť: {Math.Clamp(volume, 0, 100)}%");
                    }

                    var current = SystemActions.GetVolume();
                    var muted = SystemActions.GetMute();
                    return WithRid(jsonLine, new { type = "audio_response", ok = true, message = "OK", data = new { volume = current, muted } });
                }

                // mute_toggle
                {
                    var muted = SystemActions.ToggleMute();
                    var vol = SystemActions.GetVolume();
                    LogInfo(muted ? "Zvuk: stlmený" : "Zvuk: zapnutý");
                    return WithRid(jsonLine, new { type = "audio_response", ok = true, message = "OK", data = new { volume = vol, muted } });
                }
            }

            if (type == "brightness_get")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "brightness_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "brightness_response", ok = false, message = "Unauthorized" });

                var displayId = GetDisplayIdFromPayload(payload);

                if (string.Equals(displayId, "all", StringComparison.OrdinalIgnoreCase))
                {
                    var list = DisplayService.GetEntries();
                    var values = list.Select(d =>
                    {
                        var ok = TryGetBrightnessByDisplayId(d.Id, out var v, out var mech, out var msg);
                        return new { id = d.Id, value = ok ? v : -1, mechanism = mech, ok, message = ok ? "OK" : msg };
                    }).ToArray();

                    var anyOk = values.Any(x => x.ok);
                    var firstErr = values.FirstOrDefault(x => !x.ok)?.message ?? "No data";

                    return WithRid(jsonLine, new { type = "brightness_response", ok = anyOk, message = anyOk ? "OK" : firstErr, data = new { displayId = "all", values } });
                }
                else
                {
                    var ok = TryGetBrightnessByDisplayId(displayId, out var value, out var mech, out var msg);
                    return WithRid(jsonLine, new { type = "brightness_response", ok, message = ok ? "OK" : msg, data = new { displayId, value, mechanism = mech } });
                }
            }

            if (type == "brightness_set")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "brightness_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "brightness_response", ok = false, message = "Unauthorized" });

                if (!payload.TryGetProperty("value", out var valEl) || valEl.ValueKind != JsonValueKind.Number)
                    return WithRid(jsonLine, new { type = "brightness_response", ok = false, message = "Missing value" });

                var value = Math.Clamp(valEl.GetInt32(), 0, 100);
                var displayId = GetDisplayIdFromPayload(payload);

                if (string.Equals(displayId, "all", StringComparison.OrdinalIgnoreCase))
                {
                    var list = DisplayService.GetEntries();

                    var results = list
                        .Where(d => d.SupportsBrightness)
                        .Select(d =>
                        {
                            var ok = TrySetBrightnessByDisplayId(d.Id, value, out var mech, out var msg);
                            var got = TryGetBrightnessByDisplayId(d.Id, out var current, out _, out _);
                            return new { id = d.Id, ok, mechanism = mech, message = ok ? "OK" : msg, value = got ? current : value };
                        })
                        .ToArray();

                    var anyOk = results.Any(r => r.ok);
                    var firstErr = results.FirstOrDefault(r => !r.ok)?.message ?? "Failed";

                    if (!anyOk) LogErr($"Jas: zlyhalo ({firstErr})");

                    return WithRid(jsonLine, new { type = "brightness_response", ok = anyOk, message = anyOk ? "OK" : firstErr, data = new { displayId = "all", results } });
                }
                else
                {
                    bool ok;
                    string mech;
                    string msg;

                    if (string.Equals(displayId, "internal", StringComparison.OrdinalIgnoreCase))
                    {
                        ok = TrySetBrightnessByDisplayId(displayId, value, out mech, out msg);
                    }
                    else
                    {
                        ok = _brightnessSmoother.SetTarget(displayId, value, out mech, out msg);
                    }

                    if (!ok) LogErr($"{HumanDisplay(displayId)}: jas sa nepodarilo zmeniť ({msg})");

                    return WithRid(jsonLine, new { type = "brightness_response", ok, message = ok ? "OK" : msg, data = new { displayId, value, mechanism = mech } });
                }
            }

            // --- NIGHT MODE ---
            if (type == "night_get")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "night_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "night_response", ok = false, message = "Unauthorized" });

                var (enabled, intensity) = NightModeService.GetState();
                if (intensity > 0) _lastNightNonZeroIntensity = intensity;

                return WithRid(jsonLine, new { type = "night_response", ok = true, message = "OK", data = new { enabled, intensity } });
            }

            if (type == "night_set")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "night_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "night_response", ok = false, message = "Unauthorized" });

                var reqEnabled = TryGetBool(payload, "enabled", fallback: true);
                var reqIntensity = Math.Clamp(TryGetInt(payload, "intensity", fallback: 0), 0, 100);

                if (reqEnabled)
                {
                    if (reqIntensity <= 0)
                        reqIntensity = Math.Clamp(_lastNightNonZeroIntensity, 1, 100);
                }
                else
                {
                    reqIntensity = 0;
                }

                var ok = NightModeService.TrySet(reqEnabled, reqIntensity, out var msg);
                var (curEnabled, curIntensity) = NightModeService.GetState();
                if (curIntensity > 0) _lastNightNonZeroIntensity = curIntensity;

                if (ok) LogOk($"Nočný režim: {(curEnabled ? $"ZAP ({curIntensity}%)" : "VYP")}");
                else LogErr($"Nočný režim zlyhal: {msg}");

                return WithRid(jsonLine, new { type = "night_response", ok, message = ok ? "OK" : msg, data = new { enabled = curEnabled, intensity = curIntensity } });
            }

            // --- QUIET MODE (from mobile) ---
            if (type == "quiet_get")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "quiet_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "quiet_response", ok = false, message = "Unauthorized" });

                var svc = QuietModeService.GetState();
                if (svc != _quietUiEnabled) _quietUiEnabled = svc;

                return WithRid(jsonLine, new { type = "quiet_response", ok = true, message = "OK", data = new { enabled = _quietUiEnabled } });
            }

            if (type == "quiet_set")
            {
                if (!root.TryGetProperty("payload", out var payload))
                    return WithRid(jsonLine, new { type = "quiet_response", ok = false, message = "Missing payload" });

                var token = GetTokenFromPayload(payload);
                if (!_pairing.IsTokenValid(token))
                    return WithRid(jsonLine, new { type = "quiet_response", ok = false, message = "Unauthorized" });

                bool reqEnabled;
                if (!TryGetBoolNullable(payload, "enabled", out reqEnabled))
                    reqEnabled = !_quietUiEnabled;

                var ok = QuietModeService.TrySet(reqEnabled, out var msg);

                if (ok)
                {
                    _quietUiEnabled = reqEnabled;
                    LogOk($"Tichý režim: {(reqEnabled ? "ZAP" : "VYP")}");
                    return WithRid(jsonLine, new { type = "quiet_response", ok = true, message = "OK", data = new { enabled = _quietUiEnabled } });
                }

                LogErr($"Tichý režim zlyhal: {msg}");
                return WithRid(jsonLine, new { type = "quiet_response", ok = false, message = msg, data = new { enabled = _quietUiEnabled } });
            }

            // Unknown request type: log (throttled) so it isn't silent anymore
            var nowU = DateTime.UtcNow;
            if (_lastUnknownType != type || (nowU - _lastUnknownLogAt) > TimeSpan.FromSeconds(2))
            {
                _lastUnknownType = type;
                _lastUnknownLogAt = nowU;
                LogWarn($"Neznáma požiadavka: {type}");
            }

            return WithRid(jsonLine, new { type = "response", ok = false, message = $"Unknown type: {type}" });
        }
        catch (Exception ex)
        {
            LogErr("Chyba komunikácie (Bad JSON)");
            return JsonSerializer.Serialize(new { type = "response", ok = false, message = "Bad JSON: " + ex.Message });
        }
    }

    // =========================
    // Helpers
    // =========================
    private static string HumanTimerAction(string? action)
        => string.Equals(action, "shutdown", StringComparison.OrdinalIgnoreCase) ? "Vypnutie PC" : "Uspanie PC";

    private static string FormatSeconds(int totalSeconds)
    {
        if (totalSeconds < 0) totalSeconds = 0;
        var ts = TimeSpan.FromSeconds(totalSeconds);
        if (ts.TotalHours >= 1) return $"{(int)ts.TotalHours}:{ts.Minutes:D2}:{ts.Seconds:D2}";
        return $"{ts.Minutes}:{ts.Seconds:D2}";
    }

    // =========================
    // Server ID (stable)
    // =========================
    private static string LoadOrCreateServerId()
    {
        try
        {
            var dir = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                "DesklyPC"
            );
            Directory.CreateDirectory(dir);

            var file = Path.Combine(dir, "server_id.txt");

            if (File.Exists(file))
            {
                var s = File.ReadAllText(file).Trim();
                if (!string.IsNullOrWhiteSpace(s)) return s;
            }

            var id = Guid.NewGuid().ToString("N");
            File.WriteAllText(file, id);
            return id;
        }
        catch
        {
            return Guid.NewGuid().ToString("N");
        }
    }

    // =========================
    // Smoothers (natural fade)
    // =========================
    private sealed class BrightnessSmoother
    {
        public delegate void LogFn(LogLevel lvl, string msg);

        private sealed class State
        {
            public string DisplayId = "";
            public int DdcIndex1Based;
            public int Current;
            public int Target;
            public bool Active;
            public DateTime LastApplyAt = DateTime.MinValue;
            public string LastError = "";
        }

        private readonly object _lock = new();
        private readonly System.Threading.Timer _timer;
        private readonly Dictionary<string, State> _states = new(StringComparer.OrdinalIgnoreCase);
        private readonly LogFn _log;

        private const int STEP_NEAR = 15;
        private const int STEP_FAR = 25;
        private const int TICK_MS = 80;
        private const int APPLY_GUARD_MS = 70;

        public BrightnessSmoother(LogFn log)
        {
            _log = log;
            _timer = new System.Threading.Timer(_ => Tick(), null,
                System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
        }

        public void Start() => _timer.Change(0, TICK_MS);
        public void Stop() => _timer.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);

        public bool SetTarget(string displayId, int target0to100, out string mechanism, out string message)
        {
            mechanism = "DDC/CI (smooth)";
            message = "";
            target0to100 = Math.Clamp(target0to100, 0, 100);

            if (!DisplayService.TryResolveDdcIndex(displayId, out var idx1) || idx1 <= 0)
            {
                mechanism = "UNKNOWN";
                message = "Unknown external display";
                return false;
            }

            // Probe once so we can fail fast (instead of silently failing in Tick)
            // Prefer setting to current value (no visible jump); fallback to target.
            int probeValue = target0to100;
            if (MonitorBrightness.TryGet(idx1, out var cur, out _))
                probeValue = cur;

            if (!MonitorBrightness.TrySet(idx1, probeValue, out var probeMsg))
            {
                mechanism = "DDC/CI";
                message = string.IsNullOrWhiteSpace(probeMsg) ? "DDC/CI set failed" : probeMsg;
                return false;
            }

            lock (_lock)
            {
                if (!_states.TryGetValue(displayId, out var st))
                {
                    st = new State
                    {
                        DisplayId = displayId,
                        DdcIndex1Based = idx1,
                        Current = probeValue,
                        Target = target0to100,
                        Active = true
                    };

                    // Best effort: refresh current after probe
                    if (MonitorBrightness.TryGet(idx1, out var cur2, out _))
                        st.Current = cur2;

                    _states[displayId] = st;
                }

                st.DdcIndex1Based = idx1;
                st.Target = target0to100;
                st.Active = true;
            }

            return true;
        }

        private void Tick()
        {
            List<State> work;
            lock (_lock)
            {
                if (_states.Count == 0) return;
                work = _states.Values.Where(s => s.Active).ToList();
            }

            foreach (var st in work)
            {
                var idx1 = st.DdcIndex1Based;
                if (idx1 <= 0) { st.Active = false; continue; }

                var now = DateTime.UtcNow;
                if ((now - st.LastApplyAt).TotalMilliseconds < APPLY_GUARD_MS)
                    continue;

                var cur = st.Current;
                var tgt = st.Target;

                if (cur == tgt)
                {
                    st.Active = false;
                    continue;
                }

                var diff = tgt - cur;
                var abs = Math.Abs(diff);
                var stepAbs = abs >= 60 ? STEP_FAR : STEP_NEAR;
                var step = Math.Sign(diff) * Math.Min(stepAbs, abs);
                var next = Math.Clamp(cur + step, 0, 100);

                if (MonitorBrightness.TrySet(idx1, next, out var err))
                {
                    st.Current = next;
                    st.LastApplyAt = now;
                    st.LastError = "";
                }
                else
                {
                    // stop trying and expose error once
                    st.Active = false;

                    if (!string.Equals(st.LastError, err ?? "", StringComparison.Ordinal))
                    {
                        st.LastError = err ?? "";
                        _log(LogLevel.Error, string.IsNullOrWhiteSpace(err)
                            ? "Externý jas: zlyhalo nastavenie (DDC/CI)"
                            : $"Externý jas: zlyhalo nastavenie ({err})");
                    }
                }
            }
        }
    }

    private sealed class NightSmoother
    {
        private readonly object _lock = new();
        private readonly System.Threading.Timer _timer;

        private int _targetIntensity = 0;
        private bool _active = false;

        private const int STEP_NEAR = 15;
        private const int STEP_FAR = 25;
        private const int TICK_MS = 80;

        public NightSmoother()
        {
            _timer = new System.Threading.Timer(_ => Tick(), null,
                System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
        }

        public void Start() => _timer.Change(0, TICK_MS);
        public void Stop() => _timer.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);

        public bool SetTarget(int intensity0to100, out string message)
        {
            message = "";
            intensity0to100 = Math.Clamp(intensity0to100, 0, 100);

            lock (_lock)
            {
                _targetIntensity = intensity0to100;
                _active = true;
            }

            return true;
        }

        private void Tick()
        {
            int target;
            bool active;
            lock (_lock)
            {
                target = _targetIntensity;
                active = _active;
            }
            if (!active) return;

            var (enabled, curIntensity) = NightModeService.GetState();
            if (!enabled) curIntensity = 0;

            if (curIntensity == target)
            {
                lock (_lock) _active = false;
                return;
            }

            var diff = target - curIntensity;
            var abs = Math.Abs(diff);
            var stepAbs = abs >= 60 ? STEP_FAR : STEP_NEAR;
            var step = Math.Sign(diff) * Math.Min(stepAbs, abs);
            var next = Math.Clamp(curIntensity + step, 0, 100);

            NightModeService.TrySet(true, next, out _);

            if (next == target)
            {
                lock (_lock) _active = false;
            }
        }
    }
}
